//Register

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_FAIL = "REGISTER_FAIL";
//Login
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_FAIL = "LOGIN_FAIL";
// Logout
export const LOGOUT = "LOGOUT";
//user
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_DETAILS_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'
export const USER_LOGIN_FAIL='USER_LOGIN_FAIL'
export const USER_LOGIN_REQUEST=' USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGOUT='USER_LOGOUT'
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL'
export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
   


// Product
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const PRODUCT_DETAILS_REQUEST = " PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = " PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "  PRODUCT_DETAILS_FAIL";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS';
export const  ADD_IMAGE_FAIL = 'ADD_IMAGE_FAIL';
export const GET_IMAGE_SUCCESS='GET_IMAGE_SUCCESS';
export const GET_IMAGE_FAIL='GET_IMAGE_FAIL';

// cart
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'

export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'

// order
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_LIST_USER_REQUEST = 'ORDER_LIST_USER_REQUEST'
export const ORDER_LIST_USER_SUCCESS = 'ORDER_LIST_USER_SUCCESS'
export const ORDER_LIST_USER_FAIL = 'ORDER_LIST_USER_FAIL'
export const ORDER_LIST_USER_RESET = 'ORDER_LIST_USER_REST'
